### ISSUE TITLE
What is purpose of snapd-native, and it uses old format for RDEPENDS, anyway.

### ISSUE THREAD

**Issue by rpjday** [snapcore/meta-snapd#14]
Not sure what the point of snapd-native is, but it's broken in that it uses the old format of "RDEPENDS_${PN}". So I'm not going to touch it and let someone else deal with that.

rday

**Comment by bboozzoo** [comment]
It's purpose is to enabled the use of `snap` command to create system seeds. Must have missed it when updating for kirkstone. I'll push an update.

**Comment by rpjday** [comment]
OK, I think this can be closed.
