### ISSUE TITLE
Should this work for a RISC-V image?

### ISSUE THREAD

**Issue by rpjday** [snapcore/meta-snapd#19]
Theoretically, can I select MACHINE of qemuriscv64 and get something that runs?

ADDENDUM: Apparently, the qemuriscv64 build does not incorporate kernel-module-squashfs, so it is impossible to install snaps. Is squashfs kernel module not supported for RISC-V?

MORE: The squashfs module is in the image, just not autoloaded, so it can be manually inserted with "modprobe", but that still does not solve the problem:

\# snap install hello-world
[  928.481872] audit: type=1334 audit(1658407645.510:73): prog-id=17 op=LOAD
[  928.483608] audit: type=1334 audit(1658407645.514:74): prog-id=18 op=LOAD
error: system does not fully support snapd: cannot mount squashfs image using
       "squashfs": mount: /tmp/syscheck-mountpoint-3846894636: mount failed:
       Operation not permitted.

I am open to suggestions.

**Comment by zyga** [comment]
Master now works on riscv64. I've added CI for it https://github.com/snapcore/meta-snapd/pull/51
